### ISSUE TITLE
Cannot read property 'fileName' of undefined error

### ISSUE THREAD

**Issue by gavinmcfarland** [gladejs/gladejs#3]
Thanks for sharing your project. I know you might still be working on your project but I wanted to have a go at using it so I tried to set it up on my machine. I'm getting the following error however when I try and start the app. I just wanted to document it for you in case you're aware of it or not.

```
npm run start

...

[!] (plugin gladejs) TypeError: Cannot read property 'fileName' of undefined
TypeError: Cannot read property 'fileName' of undefined
    at Object.generateBundle (/Users/limitlessloop/Repos/example/rollup.config.js:33:68)
    at /Users/limitlessloop/Repos/example/node_modules/rollup/dist/shared/node-entry.js:13113:25
```

**Comment by AurelienStebe** [comment]
Thank you for trying it out.

I'm not sure what happened here, the error I encountered was when running "start" before copying the "pages" folder over so that I have something to build, but it was not the same stacktrace.

In any case, I am not happy with the installation process, way too fragile. I'm trying to fix that and hope you'll give it another go with the next release. Keeping the issue open for now.

**Comment by gavinmcfarland** [comment]
No problem at all. I had copied the pages, components, styles etc over also. I recently did a clean install on my machine so I'll try it again. All the best.

**Comment by AurelienStebe** [comment]
There is finally a new release (v0.3.1) for you to try out.
The README.md is updated with clear install instructions.

There is not much in terms of new feature except for the move to Rollup v2, but the "foundations" of the project are much stronger. It should work on MacOS, Ubuntu and Windows with NodeJS v10.16 or superior. I'll close this ticket, but do _not_ hesitate to open a new one with any issue or comment.
